scroll to bottom after upload file & encode HTML entity
AiursoftWeb/Kahla pull request #140
Opened 2018-11-30 15:16 UTC by xxyzz

#137

2018-12-01 07:11 UTC, Anduin2017 approved these changes

2018-12-03 12:40 UTC, xxyzz commented on src/app/Services/MessageService.ts
> +                        t.content.replace(/<[^>]+>/ig, '');
#139

2018-12-04 06:47 UTC, xxyzz commented on src/app/Services/MessageService.ts
> +                        t.content = t.content.replace(/>/g, '&gt;');
this should fix #139 🐸

2018-12-04 08:10 UTC, Anduin2017 requested changes
No, we should not use replace to make everything safe.

2018-12-04 09:13 UTC, Anduin2017 approved these changes

2018-12-04 09:19 UTC, merged